//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Torneo_Clases.servicioWebClima {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceClimaSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceClima : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback darTemperaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback darNubosidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback darVelocidadVientoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceClima() {
            this.Url = global::Torneo_Clases.Properties.Settings.Default.Torneo_Clases_servicioWebClima_WebServiceClima;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event darTemperaturaCompletedEventHandler darTemperaturaCompleted;
        
        /// <remarks/>
        public event darNubosidadCompletedEventHandler darNubosidadCompleted;
        
        /// <remarks/>
        public event darVelocidadVientoCompletedEventHandler darVelocidadVientoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darTemperatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double darTemperatura(string ciudad) {
            object[] results = this.Invoke("darTemperatura", new object[] {
                        ciudad});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void darTemperaturaAsync(string ciudad) {
            this.darTemperaturaAsync(ciudad, null);
        }
        
        /// <remarks/>
        public void darTemperaturaAsync(string ciudad, object userState) {
            if ((this.darTemperaturaOperationCompleted == null)) {
                this.darTemperaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarTemperaturaOperationCompleted);
            }
            this.InvokeAsync("darTemperatura", new object[] {
                        ciudad}, this.darTemperaturaOperationCompleted, userState);
        }
        
        private void OndarTemperaturaOperationCompleted(object arg) {
            if ((this.darTemperaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darTemperaturaCompleted(this, new darTemperaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darNubosidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string darNubosidad(string ciudad) {
            object[] results = this.Invoke("darNubosidad", new object[] {
                        ciudad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void darNubosidadAsync(string ciudad) {
            this.darNubosidadAsync(ciudad, null);
        }
        
        /// <remarks/>
        public void darNubosidadAsync(string ciudad, object userState) {
            if ((this.darNubosidadOperationCompleted == null)) {
                this.darNubosidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarNubosidadOperationCompleted);
            }
            this.InvokeAsync("darNubosidad", new object[] {
                        ciudad}, this.darNubosidadOperationCompleted, userState);
        }
        
        private void OndarNubosidadOperationCompleted(object arg) {
            if ((this.darNubosidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darNubosidadCompleted(this, new darNubosidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darVelocidadViento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double darVelocidadViento(string ciudad) {
            object[] results = this.Invoke("darVelocidadViento", new object[] {
                        ciudad});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void darVelocidadVientoAsync(string ciudad) {
            this.darVelocidadVientoAsync(ciudad, null);
        }
        
        /// <remarks/>
        public void darVelocidadVientoAsync(string ciudad, object userState) {
            if ((this.darVelocidadVientoOperationCompleted == null)) {
                this.darVelocidadVientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarVelocidadVientoOperationCompleted);
            }
            this.InvokeAsync("darVelocidadViento", new object[] {
                        ciudad}, this.darVelocidadVientoOperationCompleted, userState);
        }
        
        private void OndarVelocidadVientoOperationCompleted(object arg) {
            if ((this.darVelocidadVientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darVelocidadVientoCompleted(this, new darVelocidadVientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void darTemperaturaCompletedEventHandler(object sender, darTemperaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darTemperaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darTemperaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void darNubosidadCompletedEventHandler(object sender, darNubosidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darNubosidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darNubosidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void darVelocidadVientoCompletedEventHandler(object sender, darVelocidadVientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darVelocidadVientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darVelocidadVientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591